wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696271087.318259
    t:
      1:
      - 1
      - 5
      - 9
      - 35
      - 41
      - 48
      - 49
      - 50
      - 53
      - 54
      - 55
      - 63
      - 79
      - 103
      2:
      - 1
      - 5
      - 9
      - 35
      - 41
      - 48
      - 49
      - 50
      - 53
      - 54
      - 55
      - 63
      - 79
      - 103
      3:
      - 7
      - 13
      - 14
      - 23
      - 37
      4: 3.10.13
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
